name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase and related dependencies
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.0.0
  firebase_core: ^2.32.0
  change_app_package_name: ^1.0.0
  google_sign_in: ^5.4.2 
  google_fonts: ^6.2.1
   # Use the latest version available on pub.dev


  # Other dependencies
  image_picker: ^0.8.7
  fl_chart: ^0.40.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  carousel_slider: ^5.0.0
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  flutter_signin_button: ^2.0.0
  flutter_facebook_auth: ^6.0.0
  firebase_messaging: ^14.8.0
  shared_preferences: ^2.3.4
  shimmer: ^2.0.0
  lottie: ^2.3.2
  cached_network_image: ^3.2.1
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # flutter_credit_card: ^4.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Rc.png"

flutter:
  uses-material-design: true

  # Correct indentation for the assets section
  assets:
    - assets/compressedimages/cclothes/
    - assets/compressedimages/choodies/
    - assets/compressedimages/cjeans/
    - assets/compressedimages/cshoes/
    - assets/compressedimages/cclothes/t6.jpeg
    - assets/accesores/a1-min.jpeg
    - assets/overcost/o1-min.jpeg
    - assets/t-shop.jpeg
    - assets/arrow.jpg
    - assets/hoodie-shop.jpeg
    - assets/jean-shop.jpeg
    - assets/shoe-shop.jpeg
    - assets/RedCollar logo.png
    - assets/G l.png
    - assets/Rc.png
    - assets/first.jpg
    - assets/accesores/
    - assets/overcost/
    - assets/overcost/o1-min.jpeg
    - assets/overcost/02-min.jpeg
    - assets/client.jpg
    - assets/apple.png
    - assets/facebook.png
    - .env